name: viva
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Design pattern
  flutter_bloc: ^6.1.2
  equatable: ^1.2.5
  get_it: ^5.0.1

  # DB
  shared_preferences: ^0.5.12
  hive: ^1.4.4+1

  # Common
  bot_toast: ^3.0.3
  flutter_svg: ^0.19.1
  flutter_screenutil: ^4.0.3+2
  shimmer: ^1.1.1
  cached_network_image: ^2.1.0+1
  uuid: ^2.2.2


  # Translation
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.0

  # Json
  json_serializable: ^3.5.0

  # Theme
  dynamic_theme: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  test: ^1.3.0
  bloc_test: ^7.1.0
  pedantic: ^1.9.2
  mockito: ^4.1.1
  flutter_translate_gen: ^1.2.1
  hive_generator: ^0.8.2

flutter:

  uses-material-design: true
  assets:
    - res/graphics/
    - res/languages/
    - res/icons/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: res/fonts/GoogleSans-Bold.otf
          weight: 900
        - asset: res/fonts/GoogleSans-Regular.otf
          weight: 500
        - asset: res/fonts/GoogleSans-Medium.otf
          weight: 300
        - asset: res/fonts/GoogleSans-Italic.otf
          style: italic


